language: c
dist: trusty
sudo: required
before_install:
 - echo "deb http://ftp.de.debian.org/debian jessie main" >> /etc/apt/sources.list
 - cat /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get upgrade
 - sudo apt-get install libinfinity-0.6-dev
script: ./autogen.sh && ./configure && make

