
static void infinoted_plugin_replacer_join_user(InfinotedPluginReplacerSessionInfo*);
static void infinoted_plugin_replacer_remove_user(InfinotedPluginReplacerSessionInfo*);

static void infinoted_plugin_replacer_check_enabled(InfinotedPluginReplacerSessionInfo* info);
